### ISSUE TITLE
Error: Parent selector exceeds current stack.

### ISSUE THREAD

**Issue by mikebronner** [toomuchdesign/postcss-nested-ancestors#18]
### Do you want to request a *feature* or report a *bug*?
Bug

### What is the current behaviour?
The following postcss:
```css
.custompage_directory_widget .custom_field_input .field select {
    ^& {
        border: 1px solid red;
    }
}
```

Error thrown:
```
WARNING in ./resources/css/theme.pcss (./node_modules/css-loader??ref--8-2!./node_modules/postcss-loader/src??postcss0!./res
ources/css/theme.pcss)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(18:5) Parent selector exceeds current stack.
 @ ./resources/css/theme.pcss 2:14-145
```

Using Laravel Mix with the following web pack config:
```
let mix = require('laravel-mix');
require("laravel-mix-purgecss");

mix.webpackConfig({
    module: {
        rules: [
            {
                test: /\.jsx?$/,
                exclude: /(bower_components)/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: Config.babel()
                    }
                ]
            }
        ]
    }
});

mix
    .copy("resources/views/**/*", "public")
    .postCss("resources/css/theme.pcss", "public/css")
    .options({
        autoprefixer: {
            options: {
                browsers: [
                    'last 6 versions',
                ]
            }
        },
        postCss: [
            require("postcss-import"),
            require('postcss-nested-ancestors'),
            require("postcss-nested"),
            require("tailwindcss"),
            require('autoprefixer'),
        ]
    })
    .sourceMaps()
    .version()
    .setPublicPath('public')
;
```

### What is the expected behaviour?

Would expect the selector to resolve to `.field`.

### Specifications

  - Version: 2.0.0
  - Platform: Ubuntu 18.04
  - NPM: 6.12.0

**Comment by mikebronner** [comment]
I rewrote the css like this:
```css
.custompage_directory_widget {
    .custom_field_input {
        .field {
            select {
                ^& {
                    border: 1px solid red;
                }
            }
        }
    }
}
```

And it doesn't error out anymore, but the ancestor selector doesn't seem to work.

**Comment by mikebronner** [comment]
My goal is to only draw borders on .field class elements that have a select child.

**Comment by mikebronner** [comment]
Looking at the resulting CSS, it did this:
```css
.custompage_directory_widget .custom_field_input .field select .custompage_directory_widget .custom_field_input .field {
  border: 1px solid red;
}
```

Which of course won't work. Is this something I am doing wrong?

**Comment by toomuchdesign** [comment]
Hi @mikebronner,
what you describe seems the expected output.

`postcss-nested-ancestors` is meant to help to work with nested css when you need to **nest a portion of the parent selectors**.

In your case I don't see anything preventing from directly writing:

```css
.custompage_directory_widget {
    .custom_field_input {
        .field {
           border: 1px solid red;
           select {
           }
        }
    }
}
```
