### ISSUE TITLE
ignore media selectors

### ISSUE THREAD

**Issue by 3lvcz** [toomuchdesign/postcss-nested-ancestors#6]
I think, that media selectors - is not quite a selectors, that we can access with ^&, so maybe we should ignore them. I give an example:

```postcss
.header {
    &__title {
        @media (max-width: 320px) {
            ^&_dark & {
                color: white;
            }
            &_dark & {
                color: white;
            }
        }
    }
}
```

This code produces two same rules here, and it's not seems to be right though:

```css
@media (max-width: 320px) {
    .header__title_dark .header__title {
        color: white;
    }
    .header__title_dark .header__title {
        color: white;
    }
}
```

What I personally expected to see here:

```css
@media (max-width: 320px) {
    .header_dark .header__title {
        color: white;
    }
    .header__title_dark .header__title {
        color: white;
    }
}
```

```json
{
  "postcss": "6.0.13",
  "postcss-nested": "2.1.2",
  "postcss-nested-ancestors": "1.0.0"
}
```
